# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: persistent-memory
version: '0.0.0'
github: "githubuser/persistent-memory"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: persistent-memory is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - persistent
  - persistent-sqlite
  - persistent-template
  - text
  - template-haskell
  source-dirs: library

executables:
  persistent-memory:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - persistent-memory
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  persistent-memory-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - persistent-memory
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  persistent-memory-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - persistent-memory
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
